custom date type for /v1/analytics/data
diPhantxm/ozon-api-client pull request #79
Opened 2024-04-18 19:44 UTC by zloyleshiy

причина: time.Time маршалится в формате который не понимает api ozon (date_from=2024-03-18+00%3A00%3A00+%2B0000+UTC)
https://api-seller.ozon.ru/v1/analytics/data

```
metrics := []ozon.GetAnalyticsDataFilterMetric{ozon.OrderedUnits}

requestParams := ozon.GetAnalyticsDataParams{
  DateFrom: now.Add(time.Duration(-30) * 24 * time.Hour),
  DateTo:     time.Now(),
  Dimension: []ozon.GetAnalyticsDataDimension{ozon.SKUDimension, ozon.DayDimension},
  Metrics:   metrics,
}
```
**в ответе данные за 90 дней, а не за 30**

```

metrics := []ozon.GetAnalyticsDataFilterMetric{ozon.OrderedUnits}

YYYYMMDD := "2006-01-02"
now := time.Now()
nowStr := now.Format(YYYYMMDD)
dateFrom := now.Add(time.Duration(-30) * 24 * time.Hour)
dateFromStr := dateFrom.Format(YYYYMMDD)
now, _ = time.Parse(YYYYMMDD, nowStr)
dateFrom, _ = time.Parse(YYYYMMDD, dateFromStr)

requestParams := ozon.GetAnalyticsDataParams{
  DateFrom:  dateFrom,
  DateTo:    now,
  Dimension: []ozon.GetAnalyticsDataDimension{ozon.SKUDimension, ozon.DayDimension},
  Metrics:   metrics,
}
```
без изменений: **в ответе данные за 90 дней, а не за 30**

меняем в структуре GetAnalyticsDataParams тип полей 'DateFrom' и 'DateTo' с time.Time на string
```
metrics := []ozon.GetAnalyticsDataFilterMetric{ozon.OrderedUnits}
now := time.Now()
nowStr := now.Format(YYYYMMDD)
dateFrom := now.Add(time.Duration(-daysAgo) * 24 * time.Hour)
dateFromStr := dateFrom.Format(YYYYMMDD)

requestParams := ozon.GetAnalyticsDataParams{
  DateFrom:  dateFrom,
  DateTo:    now,
  Dimension: []ozon.GetAnalyticsDataDimension{ozon.SKUDimension, ozon.DayDimension},
  Metrics:   metrics,
}
```
получаем данные **как и ожидалось за 30 дней**

вводим новый тип данных, со своим маршалингом
```
now := time.Now()
dateFrom := now.Add(time.Duration(-daysAgo) * 24 * time.Hour)

requestParams := ozon.GetAnalyticsDataParams{
  DateFrom:  &ozon.RequestDate{Time: dateFrom},
  DateTo:    &ozon.RequestDate{Time: now},
  Dimension: []ozon.GetAnalyticsDataDimension{ozon.SKUDimension, ozon.DayDimension},
  Limit:     limit,
  Metrics:   metrics,
}
```
получаем данные **как и ожидалось за 30 дней**

2024-04-18 22:17 UTC, diPhantxm commented
@zloyleshiy Спасибо, что нашел проблему и предложил ее решение. Думаю, что такое решение вполне подходит. В будущем, скорее всего, перейдем на использование тэгов, когда это добавят (https://github.com/golang/go/discussions/63397 Секция `Struct tag options`, подсекция `format`)

2024-04-19 19:33 UTC, zloyleshiy commented
> @zloyleshiy перейдем на использование тэгов, когда это добавят ([golang/go#63397](https://github.com/golang/go/discussions/63397) Секция `Struct tag options`, подсекция `format`)

да уж, будем ждать :)

2024-04-20 16:18 UTC, diPhantxm commented
@zloyleshiy Привет. Не тороплю, но хотелось бы узнать статус PR :)

2024-04-27 08:20 UTC, diPhantxm requested changes

2024-04-27 10:44 UTC, zloyleshiy commented
> @zloyleshiy Привет. Не тороплю, но хотелось бы узнать статус PR :)

дико извиняюсь, но как то пропустил замечания к МРу
посмотрю сегодня что куда и как править

2024-04-27 19:20 UTC, zloyleshiy commented on ozon/common.go
> +
перенес

2024-04-27 19:43 UTC, zloyleshiy commented on ozon/common.go
> +type RequestDate struct {
добавил

2024-04-27 19:43 UTC, zloyleshiy commented on ozon/common.go
> +
перетащил

2024-04-27 19:43 UTC, zloyleshiy commented on ozon/common.go
> +		return nil, nil
Формально все корректно: []byte это слайс байтов, и он вполне себе может быть nil

Предлагаю пока оставить как есть и потестировать когда найдется ручка которая возвращает дату в каком то виде

2024-04-27 19:43 UTC, zloyleshiy commented on ozon/common.go
> +	if s == "null" {
не уверен, но пока тыркался были какието ошибки, в том виде в котором сейчас - вполне себе работает

2024-04-27 19:47 UTC, closed without merging